---
- name: NGINXSrv
  hosts: NGINXSrv
  become: true

  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: latest

      ansible.builtin.systemd:
        name: nginx
        state: started

      notify:
      - restart nginx
    
      tags:
      - nginx_package
      - packages
