---
- name: Install WP
  hosts: AppSrv
  become: true

  tasks:

  - name: Download WP
    get_url:
      url: https://wordpress.org/wordpress-5.7.1.tar.gz
      dest: /opt
      mode: '0640'
    tags: dnl_wp
    
  - name: Unpack WP
    unarchive:
      remote_src: true
      src: /opt/wordpress-5.7.1.tar.gz
      dest: /opt/
    tags: unp_wp

  - name: Make WordPress folder
    shell: 
      cmd: cp -R /opt/wordpress/ /usr/share/nginx/wp/
    tags: copy_wp_folder
