---
- name: Format name for php version specific repos name.
  set_fact:
    php_repos_with_version: "remi-php{{ version_num }}"

- name: Install remi repo.
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Import remi GPG key.
  rpm_key:
    key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
    state: present

- name: Enable php repo
  ini_file:
    dest: "/etc/yum.repos.d/{{ php_repos_with_version }}.repo"
    section: "{{ php_repos_with_version }}"
    option: enabled
    value: "1"

- name: Ensure PHP packages are installed.
  package:
    name: "{{ php_modules }}"
    state: present
    enablerepo: "{{ php_repo }},{{ php_repos_with_version }}"
  notify: restart webserver