---
- name: Define php.ini path when php_ini_path is not set
  set_fact:
    php_ini_path: "{{ __php_ini_path }}"
  when: php_ini_path is not defined

- name: Place PHP configuration file in place.
  template:
    src: php.ini.j2
    dest: "{{ php_ini_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart webserver