# -*- mode: ruby -*-
# vi: set ft=ruby :
MACHINES = {
  :nfss=> {
        :box_name => "centos/7",
        :ip_addr => '192.168.50.10',
        :provision => 'nfss_script.sh'
  },
  :nfsc=> {
        :box_name => "centos/7",
        :ip_addr => '192.168.50.11',
        :provision => 'nfsc_script.sh'
  }
}

Vagrant.configure(2) do |config|
  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|
              box.vm.box = boxconfig[:box_name]
              box.vm.host_name = boxname.to_s
              box.vm.network "private_network", ip: boxconfig[:ip_addr]
              config.vm.provider "virtualbox" do |vb|
                      vb.customize ["modifyvm", :id, "--memory", "256"]
                      vb.customize ["modifyvm", :id, "--cpus", "1"]
              end
              box.vm.provision "shell", inline: <<-SHELL
                mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
                yum install epel-release bash-completion -y
              SHELL
              box.vm.provision "shell", path: boxconfig[:provision]
      end
  end
end
