---
__php_modules:
  - php
  - php-cli
  - php-common
  - php-fpm
  - php-gd
  - php-imap
  - php-ldap
  - php-mbstring
  - php-opcache
  - php-pdo
  - php-pear
  - php-pecl-apcu
  - php-xml
  - php-xmlrpc

__web_service: "httpd"

__conf_paths:
  - /etc

__conf_paths_additional:
  - /etc/php.d

__php_repo: "remi"

__php_ini_path: /etc/php.ini