# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :ProcessLab => {
        :box_name => "centos/7",
        :ip_addr => '192.168.12.100'
  }
#  :nginx => {
#        :box_name => "centos/7",
#        :ip_addr => '192.168.11.103'
#  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "256"]
          end
### add kernel upgrade          
          box.vbguest.installer_options = { allow_kernel_upgrade: true }
### add synced_folder
       config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

          box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
            yum install vim epel-release bash-completion-extras     -y
          SHELL

      end
  end
end

