# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :lab12 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "256"]
          end

          config.vm.synced_folder ".", "/vagrant"

          box.vm.provision "shell", inline: <<-SHELL
           mkdir -p ~root/.ssh
           cp ~vagrant/.ssh/auth* ~root/.ssh
           yum install epel-release -y -q
# Install docker-ce
           sudo yum install -y -q yum-utils \
           device-mapper-persistent-data
           sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
           yum install docker-ce docker-compose -y -q
           systemctl start docker
           docker run hello-world
      SHELL

      end
  end
end
